from django.urls import path
from apps.usuarios.auth_views import (
    EstudianteRegisterView,
    DocenteRegisterView,
    InscripcionCreateView,
    EstudianteListView,
    CursoListView,
    GestionListView,
    LoginView,
    TutorListByCIView,
    UsuarioListView,
    MateriasCursoEstudianteView,
    EvaluacionesMateriaView,
    RegistrarAsignacionesDocenteView,
    MateriasDocenteView,
    RegistrarEvaluacionView,
    MisAsignacionesView,
    EstudiantesPorAsignacionView,
    EstudiantesPorMateriaCursoView,
    EvaluacionesPorAsignacionView,
    EstudiantesPorAsignacionView,
    RegistrarNotasEvaluacionView,
    CerrarEvaluacionView,
    VerNotasMateriaView,
    MateriasEstudianteView,
    
)

urlpatterns = [
    path('registrar-estudiante/', EstudianteRegisterView.as_view(), name='registrar-estudiante'),
    path('registrar-docente/', DocenteRegisterView.as_view(), name='registrar-docente'),
    path('inscribir/', InscripcionCreateView.as_view(), name='crear-inscripcion'),
    path('estudiantes/', EstudianteListView.as_view(), name='listar-estudiantes'),
    path('cursos/', CursoListView.as_view(), name='listar-cursos'),
    path('gestiones/', GestionListView.as_view(), name='listar-gestiones'),
    path('login/', LoginView.as_view(), name='login'),
    path('tutores/', TutorListByCIView.as_view(), name='listar-tutores'),
    path('usuarios/', UsuarioListView.as_view(), name='listar-usuarios'),
    path('materias-curso/', MateriasCursoEstudianteView.as_view(), name='materias-curso'),
    path('evaluaciones-materia/<int:materia_id>/', EvaluacionesMateriaView.as_view(), name='evaluaciones-materia'),
    path('asignaciones/registrar-materias/', RegistrarAsignacionesDocenteView.as_view(), name='registrar-asignaciones-docente'),
    path('materias/', MateriasDocenteView.as_view(), name='listar-materias-docente'),
    path('evaluaciones/registrar/', RegistrarEvaluacionView.as_view(), name='registrar-evaluacion'),
    path('asignaciones/mis/', MisAsignacionesView.as_view(), name='mis-asignaciones'),
    path('asignaciones/<int:asignacion_id>/estudiantes/', EstudiantesPorAsignacionView.as_view(), name='estudiantes-asignacion'),
    path('asignaciones/<int:asignacion_id>/materia/estudiantes/', EstudiantesPorMateriaCursoView.as_view(), name='estudiantes-por-materia-curso'),
    path('evaluaciones-materia/<int:asignacion_id>/', EvaluacionesPorAsignacionView.as_view(), name='evaluaciones-por-asignacion'),
    path('asignaciones/<int:asignacion_id>/estudiantes/', EstudiantesPorAsignacionView.as_view(), name='estudiantes-asignacion'),
    path('asignaciones/<int:asignacion_id>/evaluaciones/', EvaluacionesPorAsignacionView.as_view(), name='evaluaciones-por-asignacion'),
    path('asignaciones/<int:asignacion_id>/estudiantes/', EstudiantesPorAsignacionView.as_view(), name='estudiantes-asignacion'),
    path('notas/registrar/', RegistrarNotasEvaluacionView.as_view(), name='registrar-notas-evaluacion'),
    path('evaluaciones/<int:evaluacion_id>/cerrar/', CerrarEvaluacionView.as_view(), name='cerrar-evaluacion'),
    path('estudiante/materia/<int:materia_id>/notas/', VerNotasMateriaView.as_view(), name='ver-notas-materia'),
    path('estudiante/materias/', MateriasEstudianteView.as_view(), name='materias-estudiante'),
]
