# Generated by Django 5.2.1 on 2025-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='materias',
            field=models.ManyToManyField(related_name='cursos', to='usuarios.materia'),
        ),
    ]
