# Generated by Django 5.2.1 on 2025-06-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_curso_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
